# -*- coding: utf-8 -*-
"""Hybrid3_Synthesis Extraction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UDARf05W0k-VFJuksrBniUSTQcJYclYe
"""

"""
Hybrid3 LLM Extraction Prototype

This script retrieves a material page from the Hybrid3 database, filters relevant
HTML sections, and uses a Gemini LLM to extract structured materials information
into JSON format.

Current scope:
- product information
- dimensionality
- atomic coordinates
- synthesis method
- chemistry-aware classification of starting materials
  (amine + metal halide -> reagents; others -> solvents)

Note:
- This is a prototype built for single-material extraction.
- It can be extended to multiple materials with iteration once API quota allows.
- Optical properties such as bandgap and photoluminescence are excluded in the
  current version because they are not reliably exposed in the raw HTML.
"""

import requests
from bs4 import BeautifulSoup
import google.generativeai as genai
from google.colab import userdata
import json

# =============================
# 1. Environment setup
# =============================

genai.configure(api_key=userdata.get(''))
MODEL_NAME = ''
model = genai.GenerativeModel(MODEL_NAME)


# =============================
# 2. Get material page
# =============================

def get_material_html(m_id):
    url = f"https://materials.hybrid3.duke.edu/materials/{m_id}"
    headers = {'User-Agent': 'Mozilla/5.0'}

    try:
        resp = requests.get(url, headers=headers, timeout=15)
        if resp.status_code != 200:
            return None
        return resp.text
    except:
        return None


# =============================
# 3. Extract relevant sections
# =============================

def extract_relevant_sections(html):
    soup = BeautifulSoup(html, "html.parser")

    for tag in soup(["script", "style", "nav", "footer", "header"]):
        tag.extract()

    keywords = [
        "Chemical Formula",
        "Product",
        "Starting materials",
        "Description",
        "Method",
        "Dimensionality",
        "Crystal system",
        "Lattice parameters",
        "Space group"
    ]

    sections = []

    for sec in soup.find_all(["div", "table"]):
        txt = sec.get_text(" ", strip=True)
        if any(k in txt for k in keywords):
            sections.append(sec.get_text(" ", strip=True))

    if not sections:
        return soup.get_text()[:25000]

    return "\n".join(sections[:20])


# =============================
# 4. LLM extraction
# =============================

def extract_structured_info(filtered_html):
    prompt = f"""
You are a scientific data extraction system.

Extract structured material information from the provided Hybrid3 HTML text.

Rules:
- Use ONLY explicitly stated information.
- Do NOT infer.
- Copy the source sentence exactly where the information appears.
- confidence_score should be 1.0 when the value is clearly stated.

Chemical classification rule for starting materials:
- Put only the amine (organic amine / ammonium precursor) and the metal halide precursor into "reagents".
- Put all other chemicals, including acids and liquid media, into "solvents".
- For this task, if a chemical is not the amine or the metal halide precursor, classify it as "solvents".

Stoichiometry rule:
- Report only the amine : metal halide ratio in the format "X:Y (amine:metal halide)".
- Ignore solvents, acids, and any other non-core chemicals.
- Example: "2:1 (amine:metal halide)".

Return JSON only.

Schema:

{{
  "product_info": {{
    "formula": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }},
    "color": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }},
    "morphology": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }},
    "size": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }}
  }},

  "Dimensionality": {{
    "value": string or null,
    "confidence_score": number,
    "source_sentence": string
  }},

  "Atomic_coordinates": {{
    "Temp": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }},
    "space_group": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }},
    "crystal_system": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }},
    "lattice_parameters": {{
      "a": string or null,
      "b": string or null,
      "c": string or null,
      "alpha": string or null,
      "beta": string or null,
      "gamma": string or null
    }}
  }},

  "synthesis_method": {{
    "starting_materials": {{
      "reagents": [string],
      "solvents": [string],
      "confidence_score": number,
      "source_sentence": string
    }},

    "procedure": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }},

    "Stoichiometry": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }},

    "technique": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }},

    "conditions": {{
      "value": string or null,
      "confidence_score": number,
      "source_sentence": string
    }}
  }}
}}

HTML TEXT:
{filtered_html}
"""

    response = model.generate_content(prompt)
    txt = response.text.replace("```json", "").replace("```", "").strip()
    return json.loads(txt)


# =============================
# 5. Example
# =============================

m_id = 2
print(f"Extracting Material {m_id}...")

html = get_material_html(m_id)

if html:
    filtered = extract_relevant_sections(html)

    try:
        data = extract_structured_info(filtered)

        print("\n=== Extraction Result ===")
        print(json.dumps(data, indent=2, ensure_ascii=False))

        with open(f"material_{m_id}_structured.json", "w", encoding="utf-8") as f:
            json.dump(data, f, indent=2, ensure_ascii=False)

        print("\n Saved JSON")

    except Exception as e:
        print("Gemini extraction error:", e)

else:
    print("Failed to load page")

